# Operação com vetores e matrizes

## Notação

Seja $\mathbf{x}$ um vetor $N \times 1$ dado por:

$$
\mathbf{x} = \begin{bmatrix}
x_{0} \\
x_{1} \\
\vdots \\
x_{N}
\end{bmatrix}_{\, N \times 1} \quad .
$$

Vamos utilizar $x_{i}$ ou $x[i]$ para definir o $i$-th elemento de $\mathbf{x}$. 

O transposto de $\mathbf{x}$ é um vetor $1 \times N$ vector representado por:

$$
\mathbf{x}^{\top} = \begin{bmatrix}
x_{1} & x_{2} & \cdots & x_{N}
\end{bmatrix}_{1 \times N} \quad .
$$

In [3]:
import numpy as np
import matplotlib.pyplot as plt 

In [4]:
x = np.arange(10)

In [5]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Operações básicas com vetores

#### Multiplicação escalar-vetor


$$
\begin{split}
\mathbf{y} &= a \, \mathbf{x} \\
&= \begin{bmatrix} 
    a \, x_{0} \\
    a \, x_{1} \\
    \vdots \\
    a \, x_{N}
 \end{bmatrix}
\end{split}
$$

    for i = 0:N
        y[i] = a*x[i]
        
ou, utilizando a *colon notation*,

    y[:] = a*x[:]

In [6]:
a = 0.5

In [8]:
#y = a*x
y = a*x

In [9]:
y

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

#### Adição vetor-vetor

$$
\begin{split}
\mathbf{z} &= \mathbf{x} + \mathbf{y} \\
&= \begin{bmatrix} 
    x_{1} + y_{1} \\
    x_{2} + y_{2} \\
    \vdots \\
    x_{1} + y_{N}
 \end{bmatrix}
\end{split}
$$

    for i = 1:N
        z[i] = x[i] + y[i]

In [16]:
x = np.arange(7)
y = np.ones(7)*2

In [17]:
x

array([0, 1, 2, 3, 4, 5, 6])

In [18]:
y

array([2., 2., 2., 2., 2., 2., 2.])

In [19]:
z = y + x

In [20]:
z

array([2., 3., 4., 5., 6., 7., 8.])

Atenção! Observe a seguinte operação entre o vetor `x` e o escalar `a`

In [25]:
a = 10

In [26]:
x + a 

array([10, 11, 12, 13, 14, 15, 16])

In [27]:
a + x

array([10, 11, 12, 13, 14, 15, 16])

### Multiplicação vetor - vetor  - elemento a elemento

In [28]:
b = np.arange(7,14)
b

array([ 7,  8,  9, 10, 11, 12, 13])

In [29]:
x * b

array([ 0,  8, 18, 30, 44, 60, 78])

## Dot product

Seja $\mathbf{x}$ e $\mathbf{y}$ dois vetores $N \times 1$ definidos como:
    
$$\mathbf{x} = \left[
\begin{array}{c}
x_{1} \\
x_{2} \\
\vdots \\
x_{N}
\end{array}
\right]_{\, N \times 1}$$

e

$$
\mathbf{y} = \left[
\begin{array}{c}
y_{1} \\
y_{2} \\
\vdots \\
y_{N}
\end{array}
\right]_{\, N \times 1} \quad .
$$

O [dot product](http://mathworld.wolfram.com/DotProduct.html) de $\mathbf{x}$ e $\mathbf{y}$ é dado por:

    c = 0
    for i = 1:N
        c = c + x[i]*y[i]

In [32]:
x = np.random.rand(1000)
y = np.random.rand(1000)

In [33]:
x

array([0.45447462, 0.72676688, 0.29795168, 0.18062529, 0.9126008 ,
       0.6184208 , 0.95443053, 0.36092806, 0.34288311, 0.26506156,
       0.2089023 , 0.43080229, 0.97663246, 0.94908085, 0.58896862,
       0.66953679, 0.11568858, 0.99816317, 0.8656049 , 0.51692749,
       0.62603925, 0.14914657, 0.68369641, 0.539194  , 0.385809  ,
       0.99252265, 0.29349433, 0.89685884, 0.43923261, 0.90485922,
       0.06094377, 0.82030467, 0.5372038 , 0.91035279, 0.81187795,
       0.21493567, 0.26504009, 0.05100765, 0.73535066, 0.59000359,
       0.85052869, 0.15547675, 0.45505598, 0.78755395, 0.07562   ,
       0.00618027, 0.54226395, 0.69959754, 0.37536612, 0.24587392,
       0.84988675, 0.83180933, 0.82792706, 0.40410373, 0.72028558,
       0.87060751, 0.18890964, 0.84651933, 0.50879569, 0.71742979,
       0.70017259, 0.10585023, 0.29393684, 0.16242734, 0.76200431,
       0.17758369, 0.17882927, 0.54450479, 0.57067928, 0.48077096,
       0.04674021, 0.53005128, 0.68055116, 0.88528427, 0.10497

In [34]:
# Implementação do produto escalar

c = 0.
for i in range(len(x)): 
      c += x[i] * y[i] 
        
print("dot_product = "+ str(c)); 

dot_product = 255.38410530166325


In [35]:
# Rotina do numpy

n_c = np.dot(x, y)

print("dot_product = "+ str(n_c)); 

dot_product = 255.38410530166288


## Entre vetor e matriz

Seja $\mathbf{A}$ uma matriz $N \times M$ e $\mathbf{x}$ um vetor $M \times 1$. $\mathbf{A}$ pode ser representado usando *partição por linha* ou *partição por coluna* da seguinte maneira:

$$\begin{split}
    \mathbf{A} 
    & = \left[
    \begin{array}{ccc}
        a_{11} & \cdots & a_{1M} \\
        \vdots &        & \vdots \\
        a_{N1} & \cdots & a_{NM}
    \end{array}
    \right]_{N \times M} \\
    & = \left[
    \begin{array}{c}
        \mathbf{A}[1,:] \\
        \vdots \\
        \mathbf{A}[N,:]
    \end{array}
    \right]_{N \times M} \\
    & = \left[
    \begin{array}{ccc}
        \mathbf{A}[:,1] &
        \cdots &
        \mathbf{A}[:,M]
    \end{array}
    \right]_{N \times M}
\end{split} \: ,$$

em que $\mathbf{A}[i,:]$, $i = 1, ..., N$, é um vetor $1 \times M$ representando a $i$th linha de $\mathbf{A}$ $\mathbf{A}[:,j]$, $j = 1, ..., M$, é um vetor $N \times 1$ representando a $j$th coluna de $\mathbf{A}$.

Podemos definir o produto $\mathbf{y} = \mathbf{A} \mathbf{x}$ usando o `dot product`:

In [36]:
x = np.arange(5.)

x

array([0., 1., 2., 3., 4.])

In [37]:
A = np.reshape(np.arange(20.), (4,5))

A

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

In [38]:
y = np.dot(A,x)

y

array([ 30.,  80., 130., 180.])

## Entre matriz e matriz

Seja $\mathbf{A}$ e $\mathbf{B}$ matrizes $N \times M$ e $M \times L$ respectivamente. Essas matrizes podem ser representadas *elemento a elemento, usando a *row partition* ou a *colunm partition* da seguinte maneira:

$$\begin{split}
    \mathbf{A} 
    & = \left[
    \begin{array}{ccc}
        a_{11} & \cdots & a_{1M} \\
        \vdots &        & \vdots \\
        a_{N1} & \cdots & a_{NM}
    \end{array}
    \right]_{N \times M} \\\\
    & = \left[
    \begin{array}{c}
        \mathbf{A}[1,:] \\
        \vdots \\
        \mathbf{A}[N,:]
    \end{array}
    \right]_{N \times M} \\\\
    & = \left[
    \begin{array}{ccc}
        \mathbf{A}[:,1] &
        \cdots &
        \mathbf{A}[:,M]
    \end{array}
    \right]_{N \times M} \:
\end{split}$$

$$\begin{split}
    \mathbf{B} 
    & = \left[
    \begin{array}{ccc}
        b_{11} & \cdots & b_{1L} \\
        \vdots &        & \vdots \\
        b_{M1} & \cdots & b_{ML}
    \end{array}
    \right]_{M \times L} \\\\
    & = \left[
    \begin{array}{c}
        \mathbf{B}[1,:] \\
        \vdots \\
        \mathbf{B}[M,:]
    \end{array}
    \right]_{M \times L} \\\\
    & = \left[
    \begin{array}{ccc}
        \mathbf{B}[:,1] &
        \cdots &
        \mathbf{B}[:,L]
    \end{array}
    \right]_{M \times L}
\end{split} \: ,$$

em que $a_{ij} = \mathbf{A}[i,j]$ e $b_{ij} = \mathbf{B}[i,j]$, $i = 1, ..., N$, $j = 1, ..., M$ e $k = 1, ..., L$.

Seja $\mathbf{C}$ uma matriz $N \times L$ dada por:

$$
\mathbf{C} = \mathbf{A} \, \mathbf{B} \: ,
$$

em que os elementos $c_{ij} = \mathbf{C}[i,k]$, $i = 1, ..., N$, $k = 1, ..., L$, são definidos como:

$$\begin{split}
\mathbf{C} 
    & = \left[
    \begin{array}{ccc}
        c_{11} & \cdots & c_{1L} \\
        \vdots &        & \vdots \\
        c_{N1} & \cdots & c_{NL}
    \end{array}
    \right] \\\\
    & = \left[
    \begin{array}{cccc}
        \left( a_{11} \, b_{11} + \cdots + a_{1M} \, b_{M1} \right) &
        \left( a_{11} \, b_{12} + \cdots + a_{1M} \, b_{M2} \right) &
        \cdots &
        \left( a_{11} \, b_{1L} + \cdots + a_{1M} \, b_{ML} \right) \\
        \left( a_{21} \, b_{11} + \cdots + a_{2M} \, b_{M1} \right) &
        \left( a_{21} \, b_{12} + \cdots + a_{2M} \, b_{M2} \right) &
        \cdots &
        \left( a_{21} \, b_{1L} + \cdots + a_{2M} \, b_{ML} \right) \\
        \vdots & \vdots & & \vdots \\
        \left( a_{N1} \, b_{11} + \cdots + a_{NM} \, b_{M1} \right) &
        \left( a_{N1} \, b_{12} + \cdots + a_{NM} \, b_{M2} \right) &
        \cdots &
        \left( a_{N1} \, b_{1L} + \cdots + a_{NM} \, b_{ML} \right)
    \end{array}
    \right] \: .    
\end{split}
$$

A matriz $\mathbf{C}$ pode ser calculada usando o `dot product`:

In [48]:
A = np.array([[1.,2.],
              [3.,4.],
              [5.,6.]])
B = np.array([[7., 8.],
              [9., 10.]])

In [49]:
A

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [50]:
B

array([[ 7.,  8.],
       [ 9., 10.]])

In [51]:
C = np.dot(A, B)

In [52]:
print(C)

[[ 25.  28.]
 [ 57.  64.]
 [ 89. 100.]]
